version: '3'

services:
  shopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - shopDBv:/var/lib/mysql
  shopDBMigration:
    image: prodavnicamigration
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      shopDB:
        condition: service_healthy
  owner:
    image: owner
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBMigration
    ports:
      - 5001:5001
  courier:
    image: courier
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBMigration
    ports:
      - 5003:5003
  customer:
    image: customer
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBMigration
    ports:
      - 5002:5002

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8081:8081
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8082:8082
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  sparkapp:
    image: sparkapp
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkapp
    ports:
      - 5005:5000



volumes:
  shopDBv:

networks:
  shopNET: